pages = {
  "crowdie":[
    "Google <no-reply@accounts.google.com>",
    "www.bbc.com",
    "www.bbc.com",
    "www.bbc.com",
    "www.bbc.com",
    "www.bbc.com"
    ],
  "tm":[
    "www.bbc.com",
    "www.bbc.com",
    "www.bbc.com",
    "www.bbc.com",
    "www.bbc.com",
    "www.bbc.com"
    ],
  "msafiri":[
    "www.bbc.com",
    "www.bbc.com",
    "www.bbc.com",
    "www.bbc.com",
    "www.bbc.com",
    "www.bbc.com"
    ],
  "hschool":[
    "www.bbc.com",
    "www.bbc.com",
    "www.bbc.com",
    "www.bbc.com",
    "www.bbc.com",
    "www.bbc.com"],
  "mb":[
    "yo@dev.to",
    "update@go.facebookmail.com",
    "no-reply@m.mail.coursera.org",
    "www.bbc.com",
    "www.bbc.com",
    "www.bbc.com"
    ],
  "tbtia" :[
    "www.bbc.com",
    "www.bbc.com",
    "www.bbc.com",
    "www.bbc.com",
    "www.bbc.com",
    "www.bbc.com",
    "www.bbc.com"
    ]

}
